# Cloudflare Pages 專案配置
# 這個文件用於 Wrangler CLI 部署

name = "smart-manufacturing-website"
pages_build_output_dir = "out"

# 使用新的 pages_build_output_dir 配置格式
# 不再需要 [build] 區塊，因為 Pages 部署直接使用預建的靜態檔案

# 環境變數配置
[env.production]
# 在這裡設置生產環境的環境變數

[env.preview]
# 在這裡設置預覽環境的環境變數

# Next.js 靜態導出配置
# Cloudflare Pages 會自動處理靜態文件和路由