# Cloudflare Pages 專案配置
# 這個文件用於 Wrangler CLI 部署

name = "smart-manufacturing-website"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build:cloudflare"
publish = "out"

# 環境變數配置
[env.production]
# 在這裡設置生產環境的環境變數

[env.preview]
# 在這裡設置預覽環境的環境變數

# Next.js 靜態導出配置
# Cloudflare Pages 會自動處理靜態文件和路由