# Cloudflare Pages 專案配置
# 這個文件用於 Wrangler CLI 部署（可選）

name = "smart-manufacturing-website"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
publish = "out"

# 環境變數配置
[env.production]
# 在這裡設置生產環境的環境變數

[env.preview]
# 在這裡設置預覽環境的環境變數

# 自訂路由規則已移除
# Next.js 靜態導出會生成所有必要的 HTML 文件
# Cloudflare Pages 會自動處理這些靜態文件