# Cloudflare Pages 專案配置
# 這個文件用於 Wrangler CLI 部署

name = "smart-manufacturing-website"
# 注意：Pages 部署不需要 compatibility_date 和 compatibility_flags
# 這些配置僅用於 Cloudflare Workers

[build]
command = "npm run build:cloudflare"
publish = "out"

# 環境變數配置
[env.production]
# 在這裡設置生產環境的環境變數

[env.preview]
# 在這裡設置預覽環境的環境變數

# Next.js 靜態導出配置
# Cloudflare Pages 會自動處理靜態文件和路由